'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

import { useGSAP } from '@gsap/react'
import gsap from 'gsap'
import ReduxProvider from "./store/redux-provider";
import Header from './Components/Header'
import UserProfile, { UserProfileCtx } from "./context/userprofile";
import Logged, { LoggedCtx } from "./context/Logged";

gsap.registerPlugin(useGSAP)

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
// title: "Create Next App",
// description: "Generated by create next app",
// };

// usest
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <Logged>
          <UserProfile>
            <body className={inter.className}>
              <Header />
              {/* <main> */}
              {children}
              {/* </main> */}
            </body>
          </UserProfile>
        </Logged>
      </ReduxProvider>
    </html>
  );
}
